import React from "react";
import "./ListPage.css";

const pests = [
  { name: "Rice leaf roller", wiki: "https://apps.lucidcentral.org/pppw_v10/text/web_full/entities/rice_leaf_roller_415.htm" },
  { name: "Rice leaf caterpillar", wiki: "https://apps.lucidcentral.org/pppw_v10/text/web_full/entities/rice_leaf_roller_415.htm" },
  { name: "Paddy stem maggot", wiki: "https://plantwiseplusknowledgebank.org/doi/full/10.1079/pwkb.species.12951" },
  { name: "Asiatic rice borer", wiki: "https://plantix.net/en/library/plant-diseases/600192/asiatic-rice-borer/" },
  { name: "Yellow rice borer", wiki: "https://plantix.net/en/library/plant-diseases/600093/yellow-stem-borer/" },
  { name: "Rice gall midge", wiki: "http://www.knowledgebank.irri.org/training/fact-sheets/pest-management/insects/item/rice-gall-midge" },
  { name: "Rice Stemfly", wiki: "https://pestsofbhutan.nppc.gov.bt/crop-and-pest-identification/insects/rice-stem-borers/" },
  { name: "Brown plant hopper", wiki: "https://en.wikipedia.org/wiki/Brown_planthopper" },
  { name: "White backed plant hopper", wiki: "https://en.wikipedia.org/wiki/Sogatella_furcifera" },
  { name: "Small brown plant hopper", wiki: "https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/laodelphax-striatellus" },
  { name: "Rice water weevil", wiki: "https://www.inaturalist.org/taxa/269432-Lissorhoptrus-oryzophilus" },
  { name: "Rice leafhopper", wiki: "https://apps.lucidcentral.org/pppw_v10/text/web_full/entities/rice_green_leafhopper_417.htm" },
  { name: "Grain spreader thrips", wiki: "https://en.wikipedia.org/wiki/Thrips" },
  { name: "Rice shell pest", wiki: "https://en.wikipedia.org/wiki/Rice_weevil" },
  { name: "Grub", wiki: "https://en.wikipedia.org/wiki/Grub" },
  { name: "Mole cricket", wiki: "https://en.wikipedia.org/wiki/Mole_cricket" },
  { name: "Wireworm", wiki: "https://en.wikipedia.org/wiki/Wireworm" },
  { name: "White margined moth", wiki: "https://en.wikipedia.org/wiki/Ctenucha_multifaria" },
  { name: "Black cutworm", wiki: "https://en.wikipedia.org/wiki/Black_cutworm" },
  { name: "Large cutworm", wiki: "https://en.wikipedia.org/wiki/Cutworm" },
  { name: "Yellow worm", wiki: "https://pestweb.com/pests/747/yellow-mealworm" },
  { name: "Red spider", wiki: "https://en.wikipedia.org/wiki/Red_spider_mite" },
  { name: "Corn borer", wiki: "https://en.wikipedia.org/wiki/European_corn_borer" },
  { name: "Army worm", wiki: "https://en.wikipedia.org/wiki/Fall_armyworm" },
  { name: "Aphids", wiki: "https://en.wikipedia.org/wiki/Aphid" },
  { name: "Potato leafhopper", wiki: "https://en.wikipedia.org/wiki/Potato_leafhopper" },
  { name: "Peach borer", wiki: "https://en.wikipedia.org/wiki/Synanthedon_exitiosa" },
  { name: "Green bug", wiki: "https://en.wikipedia.org/wiki/Green_stink_bug" },
  { name: "English grain aphid", wiki: "https://en.wikipedia.org/wiki/English_grain_aphid" },
  { name: "Rice thrips", wiki: "https://en.wikipedia.org/wiki/Rice_thrips" },
  { name: "Flea Beetle", wiki: "https://en.wikipedia.org/wiki/Flea_beetle" },
  { name: "Beet weevil", wiki: "https://www.ages.at/en/plant/plant-health/pests-from-a-to-z/beet-root-weevil" },
  { name: "Cabbage army worm", wiki: "https://www.csalomontraps.com/4listbylatinname/pdffajonkentik/mamestrabrassicae08.pdf" },
  { name: "Meadow moth", wiki: "https://suffolkmoths.co.uk/micros.php?bf=13010" },
  { name: "Alfalfa weevil", wiki: "https://en.wikipedia.org/wiki/Alfalfa_weevil" },
  { name: "Locustoidea", wiki: "https://en.wikipedia.org/wiki/Locust" },
  { name: "Mango flat beak leafhopper", wiki: "https://en.wikipedia.org/wiki/Leafhopper" },
  { name: "Cicadellidae", wiki: "https://en.wikipedia.org/wiki/Cicadellidae" },
  { name: "Xylotrechus", wiki: "https://en.wikipedia.org/wiki/Xylotrechus" },
  { name: "bird cherry-oat aphid", wiki: "https://en.wikipedia.org/wiki/Rhopalosiphum_padi" },
  { name: "wheat blossom midge", wiki: "https://en.wikipedia.org/wiki/Sitodiplosis_mosellana" },
  { name: "Penthaleus major", wiki: "https://en.wikipedia.org/wiki/Penthaleus_major" },
  { name: "longlegged spider mite", wiki: "https://en.wikipedia.org/wiki/Bryobia_praetiosa" },
  { name: "wheat phloeothrips", wiki: "https://en.wikipedia.org/wiki/Haplothrips_tritici" },
  { name: "wheat sawfly", wiki: "https://en.wikipedia.org/wiki/Cephus_cinctus" },
  { name: "Cerodonta denticornis", wiki: "https://en.wikipedia.org/wiki/Cerodontha_denticornis" },
  { name: "beet fly", wiki: "https://en.wikipedia.org/wiki/Pegomya_hyoscyami" },
  { name: "beet army worm", wiki: "https://en.wikipedia.org/wiki/Spodoptera_exigua" },
  { name: "Beet spot flies", wiki: "https://en.wikipedia.org/wiki/Tetanops_myopaeformis" },
  { name: "Sericaorient alismots chulsky", wiki: "https://en.wikipedia.org/wiki/Serica_(beetle)" },
  { name: "flax budworm", wiki: "https://en.wikipedia.org/wiki/Heliothis_virescens" },
  { name: "alfalfa plant bug", wiki: "https://en.wikipedia.org/wiki/Adelphocoris_lineolatus" },
  { name: "tarnished plant bug", wiki: "https://en.wikipedia.org/wiki/Lygus_lineolaris" },
  { name: "Lytta polita", wiki: "https://en.wikipedia.org/wiki/Lytta" },
  { name: "legume blister beetle", wiki: "https://en.wikipedia.org/wiki/Epicauta" },
  { name: "blister beetle", wiki: "https://en.wikipedia.org/wiki/Meloidae" },
  { name: "Therioaphis maculata Buckton", wiki: "https://en.wikipedia.org/wiki/Therioaphis_maculata" },
  { name: "Odontothrips loti", wiki: "https://en.wikipedia.org/wiki/Odontothrips" },
  { name: "alfalfa seed chalcid", wiki: "https://en.wikipedia.org/wiki/Bruchophagus_roddi" },
  { name: "Pieris canidia", wiki: "https://en.wikipedia.org/wiki/Pieris_canidia" },
  { name: "Apolygus lucorum", wiki: "https://en.wikipedia.org/wiki/Apolygus_lucorum" },
  { name: "Limacodidae", wiki: "https://en.wikipedia.org/wiki/Limacodidae" },
  { name: "Viteus vitifoliae", wiki: "https://en.wikipedia.org/wiki/Daktulosphaira_vitifoliae" },
  { name: "Colomerus vitis", wiki: "https://en.wikipedia.org/wiki/Colomerus_vitis" },
  { name: "Brevipoalpus lewisi McGregor", wiki: "https://en.wikipedia.org/wiki/Brevipalpus_lewisi" },
  { name: "oides decempunctata", wiki: "https://en.wikipedia.org/wiki/Oides" },
  { name: "Polyphagotars onemus latus", wiki: "https://en.wikipedia.org/wiki/Polyphagotarsonemus_latus" },
  { name: "Pseudococcus comstocki Kuwana", wiki: "https://en.wikipedia.org/wiki/Pseudococcus_comstocki" },
  { name: "parathrene regalis", wiki: "https://en.wikipedia.org/wiki/Synanthedon_regalis" },
  { name: "Ampelophaga", wiki: "https://en.wikipedia.org/wiki/Ampelophaga" },
  { name: "Lycorma delicatula", wiki: "https://en.wikipedia.org/wiki/Lycorma_delicatula" },
  { name: "Cicadella viridis", wiki: "https://en.wikipedia.org/wiki/Cicadella_viridis" },
  { name: "Miridae", wiki: "https://en.wikipedia.org/wiki/Miridae" },
  { name: "Trialeurodes vaporariorum", wiki: "https://en.wikipedia.org/wiki/Greenhouse_whitefly" },
  { name: "Erythroneura apicalis", wiki: "https://en.wikipedia.org/wiki/Erythroneura" },
  { name: "Papilio xuthus", wiki: "https://en.wikipedia.org/wiki/Papilio_xuthus" },
  { name: "Panonchus citri McGregor", wiki: "https://en.wikipedia.org/wiki/Panonychus_citri" },
  { name: "Phyllocoptes oleiverus ashmead", wiki: "https://en.wikipedia.org/wiki/Phyllocoptruta_oleivora" },
  { name: "Icerya purchasi Maskell", wiki: "https://en.wikipedia.org/wiki/Icerya_purchasi" },
  { name: "Unaspis yanonensis", wiki: "https://en.wikipedia.org/wiki/Unaspis_yanonensis" },
  { name: "Ceroplastes rubens", wiki: "https://en.wikipedia.org/wiki/Ceroplastes_rubens" },
  { name: "Chrysomphalus aonidum", wiki: "https://en.wikipedia.org/wiki/Chrysomphalus_aonidum" },
  { name: "Parlatoria zizyphus Lucus", wiki: "https://en.wikipedia.org/wiki/Parlatoria_ziziphi" },
  { name: "Nipaecoccus vastalor", wiki: "https://en.wikipedia.org/wiki/Nipaecoccus_vastator" },
  { name: "Aleurocanthus spiniferus", wiki: "https://en.wikipedia.org/wiki/Aleurocanthus_spiniferus" },
  { name: "Tetradacus c Bactrocera minax", wiki: "https://en.wikipedia.org/wiki/Bactrocera_minax" },
  { name: "Dacus dorsalis(Hendel)", wiki: "https://en.wikipedia.org/wiki/Bactrocera_dorsalis" },
  { name: "Bactrocera tsuneonis", wiki: "https://en.wikipedia.org/wiki/Bactrocera_tsuneonis" },
  { name: "Prodenia litura", wiki: "https://en.wikipedia.org/wiki/Spodoptera_littoralis" },
  { name: "Adristyrannus", wiki: "https://en.wikipedia.org/wiki/Adristyrannus" },
  { name: "Phyllocnistis citrella Stainton", wiki: "https://en.wikipedia.org/wiki/Phyllocnistis_citrella" },
  { name: "Toxoptera citricidus", wiki: "https://en.wikipedia.org/wiki/Toxoptera_citricidus" },
  { name: "Toxoptera aurantii", wiki: "https://en.wikipedia.org/wiki/Toxoptera_aurantii" },
  { name: "Aphis citricola Vander Goot", wiki: "https://en.wikipedia.org/wiki/Aphis_citricola" },
  { name: "Scirtothrips dorsalis Hood", wiki: "https://en.wikipedia.org/wiki/Scirtothrips_dorsalis" },
  { name: "Dasineura sp", wiki: "https://en.wikipedia.org/wiki/Dasineura" },
  { name: "Lawana imitata Melichar", wiki: "https://en.wikipedia.org/wiki/Lawana_imitata" },
  { name: "Salurnis marginella Guerr", wiki: "https://en.wikipedia.org/wiki/Salurnis_marginella" },
  { name: "Deporaus marginatus Pascoe", wiki: "https://en.wikipedia.org/wiki/Deporaus_marginatus" },
  { name: "Chlumetia transversa", wiki: "https://en.wikipedia.org/wiki/Chlumetia_transversa" },
  { name: "Rhytidodera bowrinii white", wiki: "https://en.wikipedia.org/wiki/Rhytidodera_bowringii" },
  { name: "Sternochetus frigidus", wiki: "https://en.wikipedia.org/wiki/Sternochetus_frigidus" }
];

export default function ListPage() {
  return (
    <div className="list-container">
      {/* Pest List in Columns */}
      <div className="pest-grid">
        {pests.map((pest, index) => (
          <div key={index} className="pest-item">
            {index + 1}. <a href={pest.wiki} target="_blank" rel="noopener noreferrer">{pest.name}</a>
          </div>
        ))}
      </div>
    </div>
  );
}
